include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    avoid_print: ignore
    avoid_types_as_parameter_names: ignore
    constant_identifier_names: ignore
    deprecated_member_use: ignore
    library_private_types_in_public_api: ignore
    non_constant_identifier_names: ignore
    unused_field: ignore
    use_build_context_synchronously: ignore
