include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    constant_identifier_names: ignore
    deprecated_member_use: ignore
    unused_field: ignore
    use_build_context_synchronously: ignore
