name: aplikasi_lkbh_unmul
description: "Aplikasi lkbh test"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  another_flushbar: ^1.12.30
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.4
  firebase_auth: ^5.5.0
  firebase_core: ^3.12.0
  firebase_storage: ^12.4.3
  flutter:
    sdk: flutter
  flutter_easy_faq: ^1.0.1
  flutter_image_compress: ^2.4.0
  flutter_svg: ^2.0.17
  google_sign_in: ^6.3.0
  http: ^1.3.0
  icons_launcher: ^3.0.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  loading_animation_widget: ^1.3.0
  loading_indicator: ^3.1.1
  modal_bottom_sheet: ^3.0.0
  rename_app: ^1.6.2
  scaffold_gradient_background: ^1.0.3+1
  share_plus: ^10.1.4
  shimmer: ^3.0.0
  text_divider: ^1.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/konsultasi/
    - assets/fonts/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-Bold.ttf
          weight: 800
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-Medium.ttf
          weight: 600
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-Regular.ttf
          weight: 500
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-ExtraLight.ttf
          weight: 100


icons_launcher:
  image_path: "assets/images/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
  adaptive_icon_background: "#DA3435"
  adaptive_icon_foreground: "assets/images/logo.png"
